/**
 * Spawn handler for php-wasm proc_open/exec support.
 *
 * Registers a handler via @php-wasm/util's createSpawnHandler() that
 * intercepts process-spawning calls from PHP (proc_open, exec, etc.)
 * and runs known-safe commands in-process on the same WASM runtime.
 *
 * Limitations:
 * - Single-threaded: the spawned "process" blocks the calling PHP instance.
 * - No true parallelism or subprocess isolation.
 * - Only PHP CLI commands are supported; other binaries are rejected.
 * - Recursive/re-entrant calls (e.g. a spawned PHP script calling exec()
 *   again) are guarded with a depth counter to prevent infinite loops.
 *
 * @see https://github.com/WordPress/wordpress-playground — architectural reference
 */

import { createSpawnHandler } from "@php-wasm/util";

const MAX_SPAWN_DEPTH = 3;

/**
 * Paths that are recognized as a PHP binary in this playground environment.
 * Omeka S configures its CLI path to `/playground/php-wasm/php` in the
 * local config generated by bootstrap.js.
 */
const PHP_BIN_ALLOWLIST = new Set([
  "php",
  "/playground/php-wasm/php",
  "/usr/bin/php",
  "/usr/local/bin/php",
]);

/**
 * Returns true when `bin` looks like a PHP binary path from the allowlist
 * or ends with `/php`.
 */
function isAllowedPhpBinary(bin) {
  if (PHP_BIN_ALLOWLIST.has(bin)) {
    return true;
  }
  // Accept any absolute path ending in /php (e.g. custom paths modules may use)
  if (bin.endsWith("/php")) {
    return true;
  }
  return false;
}

/**
 * Build the spawn handler callback that will be wrapped by createSpawnHandler().
 *
 * @param {object} php - The raw @php-wasm/universal PHP instance (not the
 *   wrapped compat layer). Must expose `php.run()`.
 * @returns {Function} Async callback matching the createSpawnHandler() signature.
 */
function buildSpawnProgram(php) {
  // Track recursion depth per-handler (each PHP instance gets its own
  // counter via the closure, avoiding shared state across workers).
  let spawnDepth = 0;

  return async (command, processApi, _options) => {
    const [bin, ...args] = command;

    if (!isAllowedPhpBinary(bin)) {
      processApi.stderr(
        `Command not available in browser playground: ${bin}\n`,
      );
      // @php-wasm streams are asynchronous: the 1ms yield lets the
      // Emscripten event loop flush pipe data to PHP before the child
      // process signals exit and closes the file descriptors.
      await new Promise((resolve) => setTimeout(resolve, 1));
      processApi.exit(127);
      return;
    }

    if (spawnDepth >= MAX_SPAWN_DEPTH) {
      processApi.stderr(
        `Spawn depth limit reached (${MAX_SPAWN_DEPTH}). Recursive proc_open calls are not supported.\n`,
      );
      await new Promise((resolve) => setTimeout(resolve, 1));
      processApi.exit(1);
      return;
    }

    // Find the PHP script path among the arguments.
    // Typical patterns:
    //   php /path/to/script.php --arg1 --arg2
    //   php -d setting=value /path/to/script.php
    //   php /www/omeka/application/omeka jobs:dispatch  (no .php extension)
    //
    // The heuristic: skip flags (starting with "-"), then accept .php files
    // or absolute paths (starting with "/") that are not ini overrides
    // (containing "=", like -d foo=bar). This covers Omeka's CLI entry
    // point at /www/omeka/application/omeka which has no .php extension.
    const scriptPath = args.find(
      (arg) =>
        !arg.startsWith("-") &&
        (arg.endsWith(".php") || (arg.startsWith("/") && !arg.includes("="))),
    );

    if (!scriptPath) {
      // If no script path is found, try running as inline code
      // via the -r flag: php -r "echo 'hello';"
      const dashRIndex = args.indexOf("-r");
      if (dashRIndex >= 0 && args[dashRIndex + 1]) {
        const code = args[dashRIndex + 1];
        spawnDepth++;
        try {
          const result = await php.run({ code: `<?php ${code}` });
          if (result.text) {
            processApi.stdout(result.text);
          }
          if (result.errors) {
            processApi.stderr(result.errors);
          }
          await new Promise((resolve) => setTimeout(resolve, 1));
          processApi.exit(result.exitCode ?? 0);
        } catch (err) {
          processApi.stderr(`PHP execution error: ${err.message}\n`);
          await new Promise((resolve) => setTimeout(resolve, 1));
          processApi.exit(1);
        } finally {
          spawnDepth--;
        }
        return;
      }

      processApi.stderr(
        `No PHP script path found in command: ${command.join(" ")}\n`,
      );
      await new Promise((resolve) => setTimeout(resolve, 1));
      processApi.exit(1);
      return;
    }

    spawnDepth++;
    try {
      // Build $_SERVER variables for the spawned script.
      // argv is JSON-encoded because @php-wasm's $_SERVER entries are
      // strings; PHP's actual $argv global is populated separately by
      // the WASM runtime from the command line, but providing the
      // JSON string in $_SERVER lets bootstrap code inspect it if needed.
      const argv = [bin, ...args];

      const result = await php.run({
        scriptPath,
        $_SERVER: {
          argc: String(argv.length),
          argv: JSON.stringify(argv),
          SCRIPT_FILENAME: scriptPath,
          SCRIPT_NAME: scriptPath,
          PHP_SELF: scriptPath,
          REQUEST_METHOD: "CLI",
          DOCUMENT_ROOT: "",
        },
      });

      if (result.text) {
        processApi.stdout(result.text);
      }
      if (result.errors) {
        processApi.stderr(result.errors);
      }

      // Give PHP time to read stream data before signalling exit
      await new Promise((resolve) => setTimeout(resolve, 1));
      processApi.exit(result.exitCode ?? 0);
    } catch (err) {
      processApi.stderr(`PHP execution error: ${err.message}\n`);
      await new Promise((resolve) => setTimeout(resolve, 1));
      processApi.exit(1);
    } finally {
      spawnDepth--;
    }
  };
}

/**
 * Register the spawn handler on a raw PHP instance.
 *
 * Call this after creating the PHP runtime (via `new PHP(runtimeId)`)
 * and before bootstrap or request handling begins.
 *
 * @param {object} php - The raw @php-wasm/universal PHP instance.
 */
export async function registerSpawnHandler(php) {
  const handler = createSpawnHandler(buildSpawnProgram(php));
  await php.setSpawnHandler(handler);
}

export {
  buildSpawnProgram,
  isAllowedPhpBinary,
  MAX_SPAWN_DEPTH,
  PHP_BIN_ALLOWLIST,
};
